# Generated by Django 4.2.3 on 2023-07-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favourite_unique_favorite_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'product'), name='unique_recipe'),
        ),
    ]
